Repository YBEMiniProjectTeam/MINI-Front, pull requests merged in 2023-12, with the labels that each got.

#141 Fix: 결제 페이지&결제 완료페이지 UI 수정 및 결제금액 계산 수정
  src/api/getCompletedPaymentInfo.ts
  src/api/postPayment.ts
  src/components/Card/Card.styles.ts
  src/components/Orders/PaymentSubmitButton/PaymentSubmitButton.tsx
  src/components/Orders/ReservationInfo/ReservationInfo.tsx
  src/components/Orders/ReservationInfo/ReservationInfo.types.ts
  src/components/Orders/RoomInfo/RoomInfo.tsx
  src/components/Orders/RoomInfo/RoomInfo.types.ts
  src/components/Orders/TotalPaymentInfo/TotalPaymentInfo.tsx
  src/components/ShoppingCart/ShoppingCartComp.tsx
  src/hooks/useCompletedPaymentQuery.ts
  src/hooks/usePaymentQuery.ts
  src/hooks/useSendPaymentMutation.ts
  src/pages/completePayment/CompletePayment.styles.ts
  src/pages/completePayment/CompletePayment.tsx
  src/pages/payment/Payment.styles.ts
  src/pages/payment/Payment.tsx
Labels: fix, design

#151 Refactor: 메인 페이지 리팩토링
  src/components/Main/AccommodationGridView/AccommodationGridView.tsx
  src/components/Main/AccommodationGridView/AccommodationGridView.types.ts
  src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx
  src/components/Main/AccommodationSingleView/AccommodationSingleView.types.ts
  src/components/Main/MainCategoryMenu/MainCategoryMenu.styles.ts
  src/pages/main/Main.tsx
  src/utils/printCategory.ts
Labels: fix, refactor

#155 Refactor: 검색 결과 페이지 리팩토링 및 에러 핸들링
  src/api/axiosInstance.ts
  src/api/deleteWish.ts
  src/api/getDistrictList.ts
  src/api/getRegionList.ts
  src/api/getSearchList.ts
  src/api/getWishList.ts
  src/api/postWish.ts
  src/components/ChooseDateModal/ChooseDateModal.styles.ts
  src/components/ChooseDateModal/ChooseDateModal.tsx
  src/components/ChooseDateModal/ChooseDateModal.types.ts
  src/components/ChooseRegionModal/ChooseRegionModal.tsx
  src/components/Main/AccommodationGridView/AccommodationGridView.tsx
  src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx
  src/components/MyWishList/MyWishList.tsx
  src/components/Search/Search.tsx
  src/components/Search/Search.types.ts
  src/components/SearchList/SearchList.tsx
  src/components/SearchList/SearchList.types.ts
  src/hooks/useSearchList.ts
  src/hooks/useWishList.ts
  src/hooks/useWishMutation.ts
  src/pages/searchResult/SearchResult.tsx
  src/recoil/checkInAndOutDate.ts
  src/recoil/searchStates.ts
  src/theme/index.ts
  src/types/nullable.ts
  src/utils/convertDateFormat.ts
  src/utils/convertDateFormat3.ts
  src/utils/convertDateFormat4.ts
  tsconfig.json
Labels: fix, design, refactor

#156 Refactor: CustomForm 컴포넌트 분리 & 비동기 통신에러 다루는 ErrorBoundary 적용
  src/App.tsx
  src/components/AsyncWrapper/AsyncWrapper.types.ts
  src/components/AsyncWrapper/ErrorBoundary.tsx
  src/components/AsyncWrapper/ErrorFallback.tsx
  src/components/AsyncWrapper/SuspenseFallback.tsx
  src/components/AsyncWrapper/index.tsx
  src/components/CustomForm/CustomButton.tsx
  src/components/CustomForm/CustomCheckbox.tsx
  src/components/CustomForm/CustomForm.tsx
  src/components/CustomForm/CustomInput.tsx
  src/components/CustomForm/CustomSelect.tsx
  src/components/Orders/DiffUserInfoForm/DiffUserInfoForm.tsx
  src/components/Orders/PaymentInfo/PaymentInfo.tsx
  src/components/Orders/PaymentSubmitButton/PaymentSubmitButton.tsx
  src/components/Orders/RoomInfo/RoomInfo.styles.ts
  src/components/Orders/RoomInfo/RoomInfo.tsx
  src/main.tsx
  src/pages/completePayment/CompletePayment.tsx
  src/pages/payment/Payment.tsx
  src/utils/calculateNights.ts
  src/utils/getErrorMessage.ts
Labels: fix, feat, refactor

#162 Refactor: axios instance 사용, nullable 공통 타입 사용
  package-lock.json
  package.json
  src/api/ApiResponse.types.ts
  src/api/axiosInstance.ts
  src/api/getCompletedPaymentInfo.ts
  src/api/getPaymentInfo.ts
  src/api/getUserInfo.ts
  src/api/login/LoginApi.ts
  src/api/postPayment.ts
  src/api/register/RegisterApi.ts
  src/hooks/login/useLoginMutation.ts
  src/hooks/register/useRegisterMutation.ts
  src/hooks/useCompletedPaymentQuery.ts
  src/hooks/usePaymentQuery.ts
  src/hooks/useSendPaymentMutation.ts
  src/hooks/useUserInfoQuery.ts
  src/types/completedPayment.ts
  src/types/paymet.ts
Labels: refactor

#166 Env: playwright 세팅
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
  src/tests-examples/demo-todo-app.spec.ts
Labels: env

#173 Design: 컬러 팔레트 사용 & default colorScheme 적용
  src/components/AgreementModal/AgreementModalForm.tsx
  src/components/CustomForm/CustomButton.tsx
  src/components/CustomForm/CustomFrom.styles.ts
  src/components/Layout/Footer/Footer.styles.ts
  src/components/Layout/Layout.styles.ts
  src/components/Layout/Layout.tsx
  src/components/Orders/PaymentOptionsForm/PaymentOptionsForm.styles.ts
  src/components/Orders/PaymentSubmitButton/PaymentSubmitButton.tsx
  src/components/Orders/TermsAgreementForm/TermsAgreementForm.tsx
  src/styles/GlobalStyles.ts
  src/theme/index.ts
Labels: design

#176 Test: 테스트 코드 작성
  package-lock.json
  package.json
  src/components/ChooseDateModal/ChooseDateModal.tsx
  src/components/Search/Search.tsx
  src/main.tsx
  src/tests-examples/demo-todo-app.spec.ts
  src/tests/searchResult.spec.ts
  tsconfig.json
Labels: test

#181 Feat: 메인 페이지, 검색 결과 페이지 Skeleton UI 추가
  src/App.tsx
  src/components/Main/AccommodationGridView/AccommodationGridView.tsx
  src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx
  src/components/Main/MainSkeleton/AccommodationGridViewSkeleton.tsx
  src/components/Main/MainSkeleton/AccommodationSingleViewSkeleton.tsx
  src/components/Main/MainSkeleton/MainCarouselSkeleton.tsx
  src/components/Main/MainSkeleton/MainCategoryMenuSkeleton.tsx
  src/components/Main/MainSkeleton/MainSkeleton.styles.ts
  src/components/Main/MainSkeleton/MainSkeleton.tsx
  src/components/SearchResultSkeleton/SearchInputSkeleton.tsx
  src/components/SearchResultSkeleton/SearchListSkeleton.tsx
  src/components/SearchResultSkeleton/SearchResultSkeleton.styles.ts
  src/components/SearchResultSkeleton/SearchResultSkeleton.tsx
Labels: feat, design

#182 Refactor: 결제/결제완료 페이지 리팩토링
  src/components/CustomForm/CustomFrom.types.ts
  src/components/CustomModal/CustomModal.styles.ts
  src/components/CustomModal/CustomModal.ts
  src/components/CustomModal/CustomModal.tsx
  src/components/Orders/PaymentInfo/PaymentInfo.styles.ts
  src/components/Orders/PaymentInfo/PaymentInfo.tsx
  src/components/Orders/PaymentInfo/PaymentInfo.types.ts
  src/components/Orders/PaymentOptionsForm/PaymentOptionsForm.styles.ts
  src/components/Orders/PaymentOptionsForm/PaymentOptionsForm.tsx
  src/components/Orders/PaymentSubmitButton/PaymentSubmitButton.tsx
  src/components/Orders/RoomInfo/RoomInfo.tsx
  src/components/Orders/RoomInfo/RoomInfo.types.ts
  src/components/Orders/TotalPaymentInfo/TotalPaymentInfo.types.ts
  src/components/Orders/UserInfoForm/UserInfoForm.styles.ts
  src/hooks/useCompletedPaymentQuery.ts
  src/hooks/usePaymentQueries.ts
  src/pages/payment/Payment.tsx
  src/styles/GlobalStyles.ts
  src/theme/index.ts
  src/types/api/completedPayment.ts
  src/types/api/paymet.ts
  src/utils/calculateNights.ts
Labels: design, refactor

#185 Test: 위시리스트 페이지 테스트코드 작성
  src/components/SearchList/SearchList.tsx
  src/hooks/login/useLoginMutation.ts
  src/tests/searchResult.spec.ts
  src/tests/wishList.spec.ts
Labels: fix, refactor, test

#186 Design: 결제/결제완료 페이지 스켈레톤 UI 적용
  src/App.tsx
  src/assets/lottie/loading.json
  src/components/AsyncWrapper/AsyncWrapper.types.ts
  src/components/AsyncWrapper/DeferredComponent.tsx
  src/components/Loading/Loading.styles.ts
  src/components/Loading/index.tsx
  src/components/Orders/PaymentSkeleton/PaymentInfoSkeleton.tsx
  src/components/Orders/PaymentSkeleton/ReservationSkeleton.tsx
  src/components/Orders/PaymentSkeleton/index.tsx
Labels: feat, design

#190 Fix: withCredentials 속성 전역으로 설정
  src/api/axiosInstance.ts
Labels: fix

#192 Test: 메인 페이지 테스트 코드 작성
  src/components/Main/AccommodationGridView/AccommodationGridItem.tsx
  src/components/Main/AccommodationGridView/AccommodationGridView.tsx
  src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx
  src/hooks/useNavigateToResultPage.ts
  src/tests/main.spec.ts
Labels: fix, test

#194 테스트 파일 추가 및 수정
  src/components/AgreementModal/AgreementModalForm.tsx
  src/components/Layout/Header/Header.tsx
  src/components/Login/LoginForm.tsx
  src/components/Register/RegisterForm.tsx
  src/components/ShoppingCart/ShoppingCartComp.tsx
  src/tests/login.spec.ts
  src/tests/register.spec.ts
  src/tests/shoppingCart.spec.ts
Labels: fix, test

#195 Feat: 위시리스트 Optimistic Updates 구현
  .eslintrc.cjs
  package-lock.json
  src/components/MyWishList/MyWishList.styles.ts
  src/components/MyWishList/MyWishList.tsx
  src/components/SearchList/SearchList.tsx
  src/hooks/useWishList.ts
  src/hooks/useWishMutation.ts
  src/tests/example.spec.ts
Labels: feat, design, refactor

#198 Feat: gpt api 연동
  src/components/SearchList/SearchList.tsx
  src/components/SearchList/SearchList.types.ts
  src/pages/productDetail/ProductDetail.tsx
  src/utils/isPrintable.tsx
Labels: feat

#205 Fix: 헤더 검색창 가운데 정렬
  src/components/Layout/Header/Header.styles.ts
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Header/HeaderInput.tsx
Labels: fix, design

#206 Test: 결제/결제완료 테스트 코드 작성
  playwright.config.ts
  src/components/Orders/ReservationInfo/ReservationInfo.tsx
  src/components/Orders/RoomInfo/RoomInfo.tsx
  src/components/Orders/TotalPaymentInfo/TotalPaymentInfo.tsx
  src/components/Orders/UserInfoForm/UserInfoForm.styles.ts
  src/components/Orders/UserInfoForm/UserInfoForm.tsx
  src/pages/completePayment/CompletePayment.tsx
  src/tests/example.spec.ts
  src/tests/global-setup.ts
  src/tests/helpers/customTest.ts
  src/tests/models/cartPage.ts
  src/tests/models/completedPaymentPage.ts
  src/tests/models/loginPage.ts
  src/tests/models/paymentPage.ts
  src/tests/services/completedPaymentRequest.ts
  src/tests/services/loginRequest.ts
  src/tests/services/paymentRequest.ts
  src/tests/specs/login.spec.ts
  src/tests/specs/payment.spec.ts
Labels: test

#209 Feat: 결제 시 재고없을 경우 에러 핸들링
  .gitignore
  src/hooks/useSendPaymentMutation.ts
Labels: feat

#213 Fix: 에러바운더리 초기화 안되는 이슈
  src/components/AsyncWrapper/AsyncWrapper.types.ts
  src/components/AsyncWrapper/ErrorBoundary.tsx
  src/components/AsyncWrapper/index.tsx
  src/hooks/login/useLoginMutation.ts
Labels: fix

#215 Docs: 리드미 업데이트
  README.md
Labels: docs

#217 Fix: Playwright GlobalSetup 로그인유지 / 비로그인 나눠서 테스트 가능하도록 설정
  playwright.config.ts
  src/api/getWishList.ts
  src/tests/login.spec.ts
  src/tests/shoppingCart.spec.ts
  src/tests/specs/authentication/login.spec.ts
  src/tests/specs/authentication/register.spec.ts
  src/tests/specs/payment.spec.ts
Labels: fix, test

#220 테스트 코드 리팩토링
  package-lock.json
  package.json
  src/tests/auth.json
  src/tests/models/searchResultPage.ts
  src/tests/models/wishListPage.ts
  src/tests/searchResult.spec.ts
  src/tests/services/searchRequest.ts
  src/tests/services/wishRequest.ts
  src/tests/specs/searchResult.spec.ts
  src/tests/specs/wishList.spec.ts
  src/tests/wishList.spec.ts
  tsconfig.json
Labels: test

#221 Fix: 경로 수정
  package-lock.json
  src/tests/auth.json
  src/tests/models/loginPage.ts
  src/tests/specs/authentication/productDetail.spec.ts
  src/tests/specs/authentication/reservations.spec.ts
Labels: fix
