Repository YBEMiniProjectTeam/MINI-Front, pull requests merged in 2023-11, with the labels that each got.

#9 Design: 검색하기 컴포넌트 마크업 및 테마, 글로벌스타일 수정
  .github/ISSUE_TEMPLATE/issue-template.md
  package-lock.json
  package.json
  src/components/Search/Search.styles.tsx
  src/components/Search/Search.tsx
  src/main.tsx
  src/pages/searchResult/SearchResult.styles.tsx
  src/pages/searchResult/SearchResult.tsx
  src/styles/GlobalStyles.ts
  src/theme/index.js
  src/theme/temp.ts
Labels: design

#15 Feat: 카테고리, 지역 선택 모달 마크업
  package-lock.json
  package.json
  src/components/ChooseRegionModal/ChooseRegionModal.styles.ts
  src/components/ChooseRegionModal/ChooseRegionModal.tsx
  src/components/ChooseRegionModal/ChooseRegionModal.types.ts
  src/components/Search/Search.tsx
  src/components/SearchList/SearchList.tsx
  src/utils/temp.ts
  src/utils/truncateText.ts
Labels: feat

#20 Design: 객실 상세 페이지 마크업
  package-lock.json
  package.json
  src/App.tsx
  src/api/getRoomDetail.ts
  src/api/login/LoginApi.ts
  src/api/register/RegisterApi.ts
  src/components/CustomModal/CustomModal.styles.ts
  src/components/CustomModal/CustomModal.ts
  src/components/CustomModal/CustomModal.tsx
  src/components/Login/LoginForm.tsx
  src/components/Register/RegisterForm.tsx
  src/components/Rooms/RoomCard/RoomCard.styles.ts
  src/components/Rooms/RoomCard/RoomCard.tsx
  src/components/Rooms/RoomCard/RoomCard.types.ts
  src/components/Rooms/RoomCarousel/RoomCarousel.styles.ts
  src/components/Rooms/RoomCarousel/RoomCarousel.tsx
  src/components/Rooms/RoomCarousel/RoomCarousel.types.ts
  src/components/Rooms/RoomHeader/RoomHeader.styles.ts
  src/components/Rooms/RoomHeader/RoomHeader.tsx
  src/components/Rooms/RoomHeader/RoomHeader.types.ts
  src/components/Rooms/RoomInfoSection/RoomInfoSection.styles.ts
  src/components/Rooms/RoomInfoSection/RoomInfoSection.tsx
  src/components/Rooms/RoomInfoSection/RoomInfoSection.types.ts
  src/components/Search/Search.tsx
  src/components/SearchList/SearchList.tsx
  src/hooks/useRoomDetailQuery.ts
  src/main.tsx
  src/pages/chooseOption/ChooseOption.tsx
  src/pages/completePayment/C/CompletePayment.tsx
  src/pages/login/Login.tsx
  src/pages/payment/Payment.tsx
  src/pages/register/Register.tsx
  src/pages/roomDetail/RoomDetail.data.ts
  src/pages/roomDetail/RoomDetail.styles.ts
  src/pages/roomDetail/RoomDetail.tsx
  src/pages/searchResult/SearchResult.tsx
  src/utils/priceFormatter.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: feat, design

#26 Feat: 메인 캐러셀 기능 구현
  src/components/Main/AccommodationGridView/AccommodationGridItem.tsx
  src/components/Main/AccommodationGridView/AccommodationGridView.styles.ts
  src/components/Main/AccommodationGridView/AccommodationGridView.tsx
  src/components/Main/AccommodationGridView/AccommodationGridView.types.ts
  src/components/Main/AccommodationSingleView/AccommodationSingleView.styles.ts
  src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx
  src/components/Main/MainCarousel/MainCarousel.styles.ts
  src/components/Main/MainCarousel/MainCarousel.tsx
  src/components/Main/MainCategoryMenu/MainCategoryMenu.styles.ts
  src/components/Main/MainCategoryMenu/MainCategoryMenu.tsx
  src/components/Main/MainCategoryMenu/MainCategoryMenu.types.ts
  src/components/Main/MainCategoryMenu/MainCategoryMenuItem.tsx
  src/components/MainCarousel/MainCarousel.tsx
  src/pages/main/Main.tsx
Labels: rename, feat

#28 Feat: 인원, 일정 선택 모달 마크업
  package-lock.json
  package.json
  src/components/ChooseDateModal/ChooseDateModal.styles.ts
  src/components/ChooseDateModal/ChooseDateModal.tsx
  src/components/ChooseDateModal/ChooseDateModal.types.ts
  src/components/ChooseRegionModal/ChooseRegionModal.styles.ts
  src/components/ChooseRegionModal/ChooseRegionModal.tsx
  src/components/Search/Search.tsx
  src/utils/convertDateFormat.ts
  src/utils/convertDateFormat2.ts
Labels: feat

#31 Feat: 결제 페이지 마크업
  package-lock.json
  package.json
  src/App.tsx
  src/api/config.ts
  src/api/getRoomDetail.ts
  src/api/getUserInfo.ts
  src/components/Card/Card.styles.ts
  src/components/Card/Card.tsx
  src/components/Card/Card.types.ts
  src/components/CustomForm/CustomForm.tsx
  src/components/CustomForm/CustomFrom.styles.ts
  src/components/CustomForm/CustomFrom.types.ts
  src/components/Orders/DiffUserInfoField/DiffUserInfoField.styles.ts
  src/components/Orders/DiffUserInfoField/DiffUserInfoField.tsx
  src/components/Orders/DiffUserInfoField/DiffUserInfoField.types.ts
  src/components/Orders/PaymentOptionsField/PaymentOptionsField.tsx
  src/components/Orders/PaymentSubmitButton/PaymentSubmitButton.tsx
  src/components/Orders/PaymentSummary/PaymentSummary.styles.ts
  src/components/Orders/PaymentSummary/PaymentSummary.tsx
  src/components/Orders/PaymentSummary/PaymentSummary.types.ts
  src/components/Orders/ReservationInfo/ReservationInfo.styles.ts
  src/components/Orders/ReservationInfo/ReservationInfo.tsx
  src/components/Orders/ReservationInfo/ReservationInfo.types.ts
  src/components/Orders/TermsAgreementField/TermsAgreementField.styles.ts
  src/components/Orders/TermsAgreementField/TermsAgreementField.tsx
  src/components/Orders/UserInfoField/UserInfoField.styles.ts
  src/components/Orders/UserInfoField/UserInfoField.tsx
  src/components/Orders/UserInfoField/UserInfoField.types.ts
  src/hooks/useRoomDetailQuery.ts
  src/hooks/useUserInfoQuery.ts
  src/pages/payment/Payment.data.ts
  src/pages/payment/Payment.styles.ts
  src/pages/payment/Payment.tsx
  src/pages/payment/Payment.types.ts
  src/pages/roomDetail/RoomDetail.data.ts
  src/pages/roomDetail/RoomDetail.styles.ts
  src/pages/roomDetail/RoomDetail.tsx
Labels: feat, design

#35 Feat: 메인 페이지 카테고리 메뉴 바 컴포넌트 기능 구현
  src/components/Main/MainCategoryMenu/MainCategoryMenu.styles.ts
  src/components/Main/MainCategoryMenu/MainCategoryMenu.tsx
  src/components/Main/MainCategoryMenu/MainCategoryMenu.types.ts
  src/components/Main/MainCategoryMenu/MainCategoryMenuItem.tsx
  src/hooks/useNavigateToResultPage.ts
Labels: feat

#36 Refactor: react-query, alias 적용 및 숙소명, 카테고리 default값 쿼리스트링 이용하여 초기화
  package-lock.json
  src/api/getSearchList.ts
  src/components/ChooseDateModal/ChooseDateModal.tsx
  src/components/Search/Search.tsx
  src/components/Search/Search.types.ts
  src/components/SearchList/SearchList.tsx
  src/hooks/useSearchList.ts
  src/pages/searchResult/SearchResult.tsx
Labels: refactor

#38 Fix: navigateToResultPage navigate 방식 수정
  src/hooks/useNavigateToResultPage.ts
Labels: fix

#41 Feat, Refactor: 검색 결과 페이지 API 호출 로직 구현 및 request URL 변경
  src/api/config.ts
  src/api/getSearchList.ts
  src/api/login/LoginApi.ts
  src/api/register/RegisterApi.ts
  src/components/ChooseDateModal/ChooseDateModal.types.ts
  src/components/Search/Search.tsx
  src/components/SearchList/SearchList.tsx
  src/components/SearchList/SearchList.types.ts
  src/hooks/useSearchList.ts
  src/pages/searchResult/SearchResult.tsx
  src/utils/convertDateFormat.ts
  src/utils/convertDateFormat2.ts
  src/utils/convertDateFormat3.ts
Labels: feat

#42 Feat: 결제완료 페이지 마크업 & msw 세팅
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/assets/lottie/success_check.json
  src/components/Card/Card.tsx
  src/components/ChooseRegionModal/ChooseRegionModal.tsx
  src/components/CompletePayment/SuccessCheck.tsx
  src/components/CustomForm/CustomForm.tsx
  src/components/CustomForm/CustomFrom.types.ts
  src/components/CustomModal/CustomModal.tsx
  src/components/Layout/Layout.tsx
  src/components/Login/LoginForm.tsx
  src/components/Main/AccommodationGridView/AccommodationGridItem.tsx
  src/components/Main/MainCategoryMenu/MainCategoryMenuItem.tsx
  src/components/Orders/DiffUserInfoField/DiffUserInfoField.tsx
  src/components/Orders/PaymentInfo/PaymentInfo.styles.ts
  src/components/Orders/PaymentInfo/PaymentInfo.tsx
  src/components/Orders/PaymentInfo/PaymentInfo.types.ts
  src/components/Orders/PaymentOptionsField/PaymentOptionsField.tsx
  src/components/Orders/PaymentSubmitButton/PaymentSubmitButton.tsx
  src/components/Orders/PaymentSummary/PaymentSummary.tsx
  src/components/Orders/PaymentSummary/PaymentSummary.types.ts
  src/components/Orders/ReservationInfo/AccommodationInfo/AccommodationInfo.styles.ts
  src/components/Orders/ReservationInfo/AccommodationInfo/AccommodationInfo.tsx
  src/components/Orders/ReservationInfo/AccommodationInfo/AccommodationInfo.types.ts
  src/components/Orders/ReservationInfo/ReservationInfo.styles.ts
  src/components/Orders/ReservationInfo/ReservationInfo.tsx
  src/components/Orders/ReservationInfo/ReservationInfo.types.ts
  src/components/Orders/TermsAgreementField/TermsAgreementField.tsx
  src/components/Orders/UserInfoField/UserInfoField.tsx
  src/components/Register/RegisterForm.tsx
  src/components/Rooms/RoomCard/RoomCard.tsx
  src/components/Rooms/RoomCarousel/RoomCarousel.tsx
  src/components/Rooms/RoomHeader/RoomHeader.tsx
  src/components/Rooms/RoomInfoSection/RoomInfoSection.tsx
  src/components/Search/Search.tsx
  src/hooks/useCompletePaymentQuery.ts
  src/hooks/usePaymentQuery.ts
  src/hooks/useUserInfoQuery.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/data/dummyCompletePaymentInfo.json
  src/mocks/data/dummyMemberInfo.json
  src/mocks/data/dummyReservationInfo.json
  src/mocks/handlers.ts
  src/mocks/index.ts
  src/pages/completePayment/C/CompletePayment.tsx
  src/pages/completePayment/CompletePayment.styles.ts
  src/pages/completePayment/CompletePayment.tsx
  src/pages/payment/Payment.data.ts
  src/pages/payment/Payment.tsx
  tsconfig.json
Labels: chore, feat, design, refactor

#46 Fix: 결제 페이지 유효성 검사 로직 수정(setValue로 설정한 필드의 isValid가 false일 때)
  package.json
  src/components/CustomForm/CustomForm.tsx
  src/components/CustomForm/CustomFrom.types.ts
  src/components/Orders/DiffUserInfoField/DiffUserInfoField.tsx
  src/components/Orders/PaymentSubmitButton/PaymentSubmitButton.tsx
  src/components/Orders/PaymentSubmitButton/PaymentSubmitButton.types.ts
  src/components/Orders/TermsAgreementField/TermsAgreementField.tsx
  src/components/Orders/UserInfoField/UserInfoField.tsx
  src/components/Orders/UserInfoField/UserInfoField.types.ts
  src/pages/completePayment/CompletePayment.tsx
  src/pages/payment/Payment.tsx
Labels: fix

#52 Feat: 숙소 싱글 뷰 캐러셀 기능 구현 및 디자인 수정
  src/components/Main/AccommodationSingleView/AccommodationSingleView.styles.ts
  src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx
Labels: feat, design

#57 Fix: 카테고리 메뉴 바 수정
  src/components/Main/MainCategoryMenu/MainCategoryMenu.styles.ts
  src/components/Main/MainCategoryMenu/MainCategoryMenu.tsx
  src/components/Main/MainCategoryMenu/MainCategoryMenuItem.tsx
Labels: fix, feat, design

#60 Feat: 결제페이지 결제 수단 섹션 추가
  .gitignore
  public/mockServiceWorker.js
  src/assets/icon/ic_credit_card.png
  src/assets/icon/ic_kakao.png
  src/assets/icon/ic_mobile.png
  src/assets/icon/ic_naverpay.png
  src/assets/icon/ic_payco.png
  src/assets/icon/ic_toss.png
  src/components/Card/Card.tsx
  src/components/Card/Card.types.ts
  src/components/CustomForm/CustomForm.tsx
  src/components/CustomForm/CustomFrom.styles.ts
  src/components/CustomForm/CustomFrom.types.ts
  src/components/Orders/DiffUserCheckbox/DiffUserCheckBox.types.ts
  src/components/Orders/DiffUserCheckbox/DiffUserCheckbox.styles.ts
  src/components/Orders/DiffUserCheckbox/DiffUserCheckbox.tsx
  src/components/Orders/DiffUserInfoField/DiffUserInfoField.types.ts
  src/components/Orders/DiffUserInfoForm/DiffUserInfoForm.styles.ts
  src/components/Orders/DiffUserInfoForm/DiffUserInfoForm.tsx
  src/components/Orders/DiffUserInfoForm/DiffUserInfoForm.types.ts
  src/components/Orders/PaymentOptionsField/PaymentOptionsField.tsx
  src/components/Orders/PaymentOptionsForm/PaymentOptionsForm.constant.ts
  src/components/Orders/PaymentOptionsForm/PaymentOptionsForm.styles.ts
  src/components/Orders/PaymentOptionsForm/PaymentOptionsForm.tsx
  src/components/Orders/PaymentSubmitButton/PaymentSubmitButton.tsx
  src/components/Orders/ReservationInfo/ReservationInfo.styles.ts
  src/components/Orders/TermsAgreementForm/TermsAgreementForm.styles.ts
  src/components/Orders/TermsAgreementForm/TermsAgreementForm.tsx
  src/components/Orders/UserInfoForm/UserInfoForm.styles.ts
  src/components/Orders/UserInfoForm/UserInfoForm.tsx
  src/components/Orders/UserInfoForm/UserInfoForm.types.ts
  src/components/Orders/VisitOptionsForm/RadioOptions.styles.ts
  src/components/Orders/VisitOptionsForm/RadioOptions.tsx
  src/components/Orders/VisitOptionsForm/VisitOptionsForm.tsx
  src/hooks/usePaymentQuery.ts
  src/hooks/useUserInfoQuery.ts
  src/pages/payment/Payment.styles.ts
  src/pages/payment/Payment.tsx
Labels: feat, design, refactor

#61 Refactor, Fix: 검색 결과 페이지 리팩토링 및 에러 핸들링
  package-lock.json
  package.json
  src/api/getDistrictList.ts
  src/api/getRegionList.ts
  src/api/getSearchList.ts
  src/api/getWishLIst.ts
  src/components/ChooseRegionModal/ChooseRegionModal.styles.ts
  src/components/ChooseRegionModal/ChooseRegionModal.tsx
  src/components/ChooseRegionModal/ChooseRegionModal.types.ts
  src/components/MyWishList/MyWishList.tsx
  src/components/Search/Search.tsx
  src/components/SearchList/SearchList.tsx
  src/components/SearchList/SearchList.types.ts
  src/hooks/useDistrictList.ts
  src/hooks/useRegionList.ts
  src/hooks/useSearchList.ts
  src/hooks/useWishLIst.ts
  src/main.tsx
  src/pages/searchResult/SearchResult.tsx
  src/recoil/checkInAndOutDate.ts
  src/recoil/temp.ts
  src/utils/convertDateFormat4.ts
Labels: feat, refactor

#62 헤더, 로그인 API 연동 및 수정
  src/api/login/LoginApi.ts
  src/api/register/RegisterApi.ts
  src/components/Layout/Header/Header.tsx
  src/components/Layout/Header/HeaderInput.tsx
  src/components/Login/LoginForm.tsx
  src/components/Register/Register.types.ts
  src/components/Register/RegisterForm.tsx
Labels: fix, feat

#65 Feat: 메인 페이지 API 연동
  src/api/config.ts
  src/components/Main/AccommodationGridView/AccommodationGridView.styles.ts
  src/components/Main/AccommodationGridView/AccommodationGridView.tsx
  src/components/Main/AccommodationGridView/AccommodationGridView.types.ts
  src/components/Main/AccommodationSingleView/AccommodationSingleView.styles.ts
  src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx
  src/utils/printCategory.ts
Labels: feat, refactor

#67 Feat: 메인 캐러셀 이미지 수정
  src/assets/image/main_carousel1.png
  src/assets/image/main_carousel2.png
  src/components/Main/MainCarousel/MainCarousel.tsx
Labels: feat

#69 Feat: 장바구니 페이지 구현
  src/api/getSearchList.ts
  src/api/shoppingCart/shoppingCartApi.ts
  src/components/ShoppingCart/ShoppinCart.types.ts
  src/components/ShoppingCart/ShoppingCart.styles.ts
  src/components/ShoppingCart/ShoppingCartComp.tsx
  src/components/ShoppingCart/ShoppingCartList.tsx
  src/pages/shoppingCart/ShoppingCart.tsx
Labels: feat, design

#71 로컬 테스트를 위한 로컬스토리지 값(엑세스토큰) 추가
  src/api/login/LoginApi.ts
  src/api/register/RegisterApi.ts
  src/components/Layout/Header/Header.tsx
  src/components/Login/LoginForm.tsx
  src/components/Register/RegisterForm.tsx
Labels: feat, test

#72 Feat: 결제 페이지 API 연동
  .gitignore
  index.html
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/api/getCompletedPayment.ts
  src/api/getPaymentInfo.ts
  src/api/getUserInfo.ts
  src/api/login/LoginApi.ts
  src/api/register/RegisterApi.ts
  src/components/Orders/PaymentInfo/PaymentInfo.styles.ts
  src/components/Orders/PaymentSubmitButton/PaymentSubmitButton.tsx
  src/components/Orders/PaymentSubmitButton/PaymentSubmitButton.types.ts
  src/components/Orders/ReservationInfo/AccommodationInfo/AccommodationInfo.tsx
  src/components/Orders/ReservationInfo/AccommodationInfo/AccommodationInfo.types.ts
  src/components/Orders/ReservationInfo/ReservationInfo.styles.ts
  src/components/Orders/ReservationInfo/ReservationInfo.tsx
  src/components/Orders/ReservationInfo/ReservationInfo.types.ts
  src/components/Orders/UserInfoForm/UserInfoForm.tsx
  src/components/Orders/UserInfoForm/UserInfoForm.types.ts
  src/components/Orders/VisitOptionsForm/RadioOptions.styles.ts
  src/components/Orders/VisitOptionsForm/RadioOptions.tsx
  src/components/Orders/VisitOptionsForm/VisitOptionsForm.tsx
  src/hooks/useCompletedPaymentQuery.ts
  src/hooks/usePaymentQuery.ts
  src/hooks/useUserInfoQuery.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/data/dummyCompletedPaymentData.json
  src/mocks/data/dummyMemberInfoData.json
  src/mocks/data/dummyPaymentData.json
  src/mocks/handlers.ts
  src/mocks/index.ts
  src/pages/completePayment/CompletePayment.tsx
  src/pages/payment/Payment.tsx
  src/styles/GlobalStyles.ts
  src/utils/calculateNights.ts
  src/utils/getAuthCookie.ts
  tsconfig.json
Labels: feat, design

#76 Feat: 메인 페이지 navigate 추가
  src/components/Main/AccommodationGridView/AccommodationGridItem.tsx
  src/components/Main/AccommodationGridView/AccommodationGridView.styles.ts
  src/components/Main/AccommodationGridView/AccommodationGridView.tsx
  src/components/Main/AccommodationGridView/AccommodationGridView.types.ts
  src/components/Main/AccommodationSingleView/AccommodationSingleView.styles.ts
  src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx
  src/components/Main/MainCategoryMenu/MainCategoryMenuItem.tsx
  src/hooks/useNavigateToDetailPage.ts
  src/hooks/useNavigateToResultPage.ts
  src/utils/getTodayTomorrow.ts
Labels: feat

#77 Design: 메인 페이지 디테일 수정
  src/components/Main/AccommodationGridView/AccommodationGridItem.tsx
  src/components/Main/AccommodationGridView/AccommodationGridView.styles.ts
  src/components/Main/AccommodationGridView/AccommodationGridView.tsx
  src/components/Main/AccommodationSingleView/AccommodationSingleView.styles.ts
  src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx
Labels: design, refactor

#78 Feat: 토큰값 로컬스토리지에서 받아오는 함수 구현
  src/components/MyWishList/MyWishList.tsx
  src/components/SearchList/SearchList.tsx
  src/pages/payment/Payment.tsx
  src/utils/getAuthLocalStorage.ts
Labels: feat

#83 Feat: 404 페이지 추가
  src/App.tsx
  src/pages/notFound/NotFound.styles.tsx
  src/pages/notFound/NotFound.tsx
Labels: feat, design

#84 Feat, Design: searchList 컴포넌트 region 설정 및 폰트 설정
  src/components/Search/Search.tsx
  src/components/Search/Search.types.ts
  src/components/SearchList/SearchList.tsx
  src/components/SearchList/SearchList.types.ts
  src/main.tsx
  src/pages/searchResult/SearchResult.tsx
  src/recoil/searchStates.ts
  src/theme/Fonts.tsx
  src/theme/index.ts
Labels: feat, design

#90 Feat: 결제완료 페이지 UI 수정 & Mocking API 연동
  src/App.tsx
  src/api/getCompletedPaymentInfo.ts
  src/api/postPayment.ts
  src/components/CompletePayment/SuccessCheck.tsx
  src/components/Orders/PaymentInfo/PaymentInfo.tsx
  src/components/Orders/PaymentInfo/PaymentInfo.types.ts
  src/components/Orders/PaymentSubmitButton/PaymentSubmitButton.tsx
  src/components/Orders/ReservationInfo/ReservationInfo.styles.ts
  src/components/Orders/ReservationInfo/ReservationInfo.tsx
  src/components/Orders/ReservationInfo/ReservationInfo.types.ts
  src/components/Orders/RoomInfo/RoomInfo.tsx
  src/components/Orders/RoomInfo/RoomInfo.types.ts
  src/components/Orders/TotalPaymentInfo/TotalPaymentInfo.tsx
  src/components/Orders/TotalPaymentInfo/TotalPaymentInfo.types.ts
  src/hooks/useCompletedPaymentQuery.ts
  src/hooks/usePaymentQuery.ts
  src/hooks/useSendPaymentMutation.ts
  src/mocks/data/dummyCompletedPaymentData.json
  src/mocks/data/dummyPaymentData.json
  src/mocks/handlers.ts
  src/pages/completePayment/CompletePayment.styles.ts
  src/pages/completePayment/CompletePayment.tsx
  src/pages/payment/Payment.tsx
  tsconfig.json
Labels: feat, design

#92 Fixed: 장바구니 API 연동 및 테스트 완료 / 스타일 수정
  src/api/config.ts
  src/api/login/LoginApi.ts
  src/api/shoppingCart/shoppingCartApi.ts
  src/components/ShoppingCart/ShoppinCart.types.ts
  src/components/ShoppingCart/ShoppingCart.styles.ts
  src/components/ShoppingCart/ShoppingCartComp.tsx
  src/components/ShoppingCart/ShoppingCartList.tsx
Labels: fix, design

#95 Refactor: Swal alert toast로 교체
  package-lock.json
  package.json
  src/App.tsx
  src/components/AgreementModal/AgreementModalForm.tsx
  src/components/Login/LoginForm.tsx
  src/components/MyWishList/MyWishList.tsx
  src/components/ProductDetail/WishListButton/WishListButton.tsx
  src/components/Register/RegisterForm.tsx
  src/components/Search/Search.tsx
  src/components/SearchList/SearchList.tsx
  src/components/ShoppingCart/ShoppingCartComp.tsx
  src/hooks/useWishMutation.ts
  src/main.tsx
  src/pages/notLogin/NotLogin.tsx
  src/utils/authCheck.ts
Labels: refactor

#96 Fix: 숙소 조회 API 로직 수정
  src/api/getSearchList.ts
  src/components/Main/AccommodationGridView/AccommodationGridView.tsx
  src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx
  src/utils/sliceAccommodationName.ts
Labels: fix

#100 Refactor: lazy loading 기능 추가
  src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx
  src/components/MyWishList/MyWishList.tsx
  src/components/Rooms/RoomCarousel/RoomCarousel.tsx
  src/components/SearchList/SearchList.tsx
  src/pages/reservationDetails/ReservationDetails.tsx
  src/pages/reservations/Reservations.tsx
Labels: refactor

#105 Fix: 카테고리 메뉴 navigate 시 한글로 수정
  src/components/Main/MainCategoryMenu/MainCategoryMenu.tsx
Labels: fix

#107 Fix: 결제완료 엔드포인트 수정
  src/api/getCompletedPaymentInfo.ts
Labels: fix

#108 Fix: 결제완료 페이지 룸 타입 수정
  src/components/Orders/RoomInfo/RoomInfo.tsx
  src/components/Orders/RoomInfo/RoomInfo.types.ts
  tsconfig.json
Labels: fix

#111 Fix: 검색 결과 페이지 url 전달 에러 수정
  src/components/Search/Search.tsx
  src/components/SearchList/SearchList.tsx
Labels: fix

#113 Fix: 메인 페이지 데이터 없어서 발생하는 오류 수정
  src/components/Main/AccommodationGridView/AccommodationGridView.tsx
  src/components/Main/AccommodationSingleView/AccommodationSingleView.styles.ts
  src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx
Labels: fix

#116 Design: 메인 페이지 세부 디자인 수정
  src/components/Main/AccommodationGridView/AccommodationGridView.styles.ts
  src/components/Main/AccommodationGridView/AccommodationGridView.tsx
  src/components/Main/AccommodationSingleView/AccommodationSingleView.styles.ts
  src/components/Main/AccommodationSingleView/AccommodationSingleView.tsx
Labels: design

#119 Fix: 결제완료 페이지 데이터 안뜨는 거 수정
  src/components/Orders/RoomInfo/RoomInfo.tsx
  src/components/Orders/RoomInfo/RoomInfo.types.ts
  src/components/Orders/TotalPaymentInfo/TotalPaymentInfo.tsx
  src/hooks/useCompletedPaymentQuery.ts
  src/pages/completePayment/CompletePayment.tsx
  src/pages/payment/Payment.tsx
Labels: fix

#126 Fix: 빌드 에러 수정
  src/App.tsx
  src/components/Rooms/RoomCard/RoomCard.styles.ts
  src/components/Rooms/RoomCard/RoomCard.tsx
  src/components/Rooms/RoomCard/RoomCard.types.ts
  src/components/Rooms/RoomCarousel/RoomCarousel.styles.ts
  src/components/Rooms/RoomCarousel/RoomCarousel.tsx
  src/components/Rooms/RoomCarousel/RoomCarousel.types.ts
  src/components/Rooms/RoomHeader/RoomHeader.styles.ts
  src/components/Rooms/RoomHeader/RoomHeader.tsx
  src/components/Rooms/RoomHeader/RoomHeader.types.ts
  src/components/Rooms/RoomInfoSection/RoomInfoSection.styles.ts
  src/components/Rooms/RoomInfoSection/RoomInfoSection.tsx
  src/components/Rooms/RoomInfoSection/RoomInfoSection.types.ts
  src/pages/completePayment/CompletePayment.tsx
  src/pages/payment/Payment.tsx
  src/pages/roomDetail/RoomDetail.data.ts
  src/pages/roomDetail/RoomDetail.styles.ts
  src/pages/roomDetail/RoomDetail.tsx
Labels: fix

#128 Feat: 바로 결제하기 API 연동
  src/api/accomodation/postPayment.ts
  src/components/ProductDetail/ChooseRoom/ChooseRoom.tsx
  src/components/ProductDetail/ChooseRoom/ChooseRoom.types.ts
  src/components/ProductDetail/Map/Map.tsx
  src/hooks/usePaymentMutation.ts
Labels: feat

#131 Fix: 캐러셀 크기 고정 값으로 수정
  src/components/Main/AccommodationSingleView/AccommodationSingleView.styles.ts
Labels: fix, design

#135 Env, Design, Fix, Chore: 위시리스트 페이지 디자인 변경 및 배포 설정 변경
  src/api/getSearchList.ts
  src/components/MyWishList/MyWishList.tsx
  src/components/Search/Search.tsx
  src/components/SearchList/SearchList.tsx
  vercel.json
Labels: fix, chore, design, env

#137 Fix: 캐러셀 slick 스타일 수정
  src/components/Main/AccommodationSingleView/AccommodationSingleView.styles.ts
  src/components/Main/MainCarousel/MainCarousel.styles.ts
Labels: fix, design

#140 Fix: 좋아요 post, delete시 헤더 안담기는 오류 수정
  src/api/deleteWish.ts
  src/api/getSearchList.ts
  src/api/getWishList.ts
  src/api/postWish.ts
  src/components/MyWishList/MyWishList.tsx
  src/components/Search/Search.tsx
  src/components/SearchList/SearchList.tsx
  src/hooks/useSearchList.ts
  src/hooks/useWishList.ts
  src/hooks/useWishMutation.ts
Labels: fix
